<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260422120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add user_preference table for per-user pagination settings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, items_per_page INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11765022A76ED395 ON user_preference (user_id)');
        $this->addSql('ALTER TABLE user_preference ADD CONSTRAINT FK_11765022A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_preference DROP CONSTRAINT FK_11765022A76ED395');
        $this->addSql('DROP TABLE user_preference');
    }
}
