<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260421125339 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(50) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C744045577153098 ON client (code)');
        $this->addSql('CREATE TABLE location (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, allee VARCHAR(10) DEFAULT NULL, rack VARCHAR(10) DEFAULT NULL, niveau VARCHAR(10) DEFAULT NULL, position VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5E9E89CB77153098 ON location (code)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(100) NOT NULL, designation VARCHAR(255) NOT NULL, ean13 VARCHAR(13) DEFAULT NULL, gtin VARCHAR(14) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D34A04ADAEA34913 ON product (reference)');
        $this->addSql('CREATE TABLE reception (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(100) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type_reception VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_50D6852FAEA34913 ON reception (reference)');
        $this->addSql('CREATE TABLE stock_movement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, quantite DOUBLE PRECISION NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, commentaire VARCHAR(255) DEFAULT NULL, charge_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BB1BC1B555284914 ON stock_movement (charge_id)');
        $this->addSql('CREATE TABLE stock_unit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_charge VARCHAR(50) NOT NULL, serial_number VARCHAR(100) DEFAULT NULL, designation VARCHAR(255) DEFAULT NULL, statut VARCHAR(20) NOT NULL, type_unite VARCHAR(10) NOT NULL, lot VARCHAR(100) DEFAULT NULL, lot_fabrication VARCHAR(100) DEFAULT NULL, date_fabrication TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, dluo TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_dernier_mouvement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_dernier_prelevement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, allee VARCHAR(10) DEFAULT NULL, rack VARCHAR(10) DEFAULT NULL, niveau VARCHAR(10) DEFAULT NULL, position VARCHAR(10) DEFAULT NULL, poids DOUBLE PRECISION DEFAULT NULL, largeur DOUBLE PRECISION DEFAULT NULL, hauteur DOUBLE PRECISION DEFAULT NULL, profondeur DOUBLE PRECISION DEFAULT NULL, quantite DOUBLE PRECISION NOT NULL, quantite_reservee DOUBLE PRECISION NOT NULL, quantite_aregrouper DOUBLE PRECISION NOT NULL, type_reception VARCHAR(20) DEFAULT NULL, type_flux VARCHAR(5) DEFAULT NULL, etat VARCHAR(10) NOT NULL, famille_logistique VARCHAR(100) DEFAULT NULL, temps_atelier DOUBLE PRECISION DEFAULT NULL, technicien VARCHAR(100) DEFAULT NULL, etat_final VARCHAR(100) DEFAULT NULL, prix_achat DOUBLE PRECISION DEFAULT NULL, unite_facturation VARCHAR(20) DEFAULT NULL, multi_reference BOOLEAN NOT NULL, a_inventorier BOOLEAN NOT NULL, est_rebut BOOLEAN NOT NULL, est_bloque BOOLEAN NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(100) DEFAULT NULL, reception_id INT DEFAULT NULL, product_id INT NOT NULL, owner_id INT DEFAULT NULL, emplacement_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C5A154972AEDFC96 ON stock_unit (code_charge)');
        $this->addSql('CREATE INDEX IDX_C5A154977C14DF52 ON stock_unit (reception_id)');
        $this->addSql('CREATE INDEX IDX_C5A154974584665A ON stock_unit (product_id)');
        $this->addSql('CREATE INDEX IDX_C5A154977E3C61F9 ON stock_unit (owner_id)');
        $this->addSql('CREATE INDEX IDX_C5A15497C4598A51 ON stock_unit (emplacement_id)');
        $this->addSql('ALTER TABLE stock_movement ADD CONSTRAINT FK_BB1BC1B555284914 FOREIGN KEY (charge_id) REFERENCES stock_unit (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_unit ADD CONSTRAINT FK_C5A154977C14DF52 FOREIGN KEY (reception_id) REFERENCES reception (id)');
        $this->addSql('ALTER TABLE stock_unit ADD CONSTRAINT FK_C5A154974584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_unit ADD CONSTRAINT FK_C5A154977E3C61F9 FOREIGN KEY (owner_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE stock_unit ADD CONSTRAINT FK_C5A15497C4598A51 FOREIGN KEY (emplacement_id) REFERENCES location (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stock_movement DROP CONSTRAINT FK_BB1BC1B555284914');
        $this->addSql('ALTER TABLE stock_unit DROP CONSTRAINT FK_C5A154977C14DF52');
        $this->addSql('ALTER TABLE stock_unit DROP CONSTRAINT FK_C5A154974584665A');
        $this->addSql('ALTER TABLE stock_unit DROP CONSTRAINT FK_C5A154977E3C61F9');
        $this->addSql('ALTER TABLE stock_unit DROP CONSTRAINT FK_C5A15497C4598A51');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE reception');
        $this->addSql('DROP TABLE stock_movement');
        $this->addSql('DROP TABLE stock_unit');
    }
}
